# Generated by Django 4.2.5 on 2023-10-26 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='nombre',
        ),
    ]
