# Generated by Django 4.2.5 on 2023-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_wishlist_producto_wishlist_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('notas_pedido', models.TextField(blank=True)),
                ('tipo_envio', models.CharField(choices=[('tienda', 'Retiro en tienda'), ('domicilio', 'Envío a domicilio')], default='tienda', max_length=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia'), ('mercadopago', 'MercadoPago'), ('efectivo', 'Efectivo')], default='transferencia', max_length=15)),
            ],
        ),
    ]
