# Generated by Django 4.2.5 on 2023-11-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='persona',
            new_name='nombre',
        ),
    ]
