# Generated by Django 4.2.5 on 2023-11-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_persona_persona_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default=0, max_length=15, verbose_name='Telefono'),
        ),
    ]
